schema: steward.io/resource-kind
kind: ResourceKind
metadata:
  provider: gcp
  nativeType: composer.googleapis.com/Environment
  class: orchestration.workflow_environment
presentation:
  displayNames:
    en-US: Cloud Composer environment
    zh-CN: Cloud Composer 环境
  consoleLinkTemplate: https://console.cloud.google.com/home/dashboard?project={projectId}
scope:
  kind: region
discovery:
  source: product-api
  list:
    operation: composer.projects.locations.environments.list
    parameters:
      parent: scope.locationParent
    itemsPath: environments
    identityPath: name
    pagination:
      type: token
      tokenParameter: pageToken
      tokenPath: nextPageToken
      pageSizeParameter: pageSize
      maxPageSize: 100
  detail:
    operation: composer.projects.locations.environments.get
    itemsPath: $
    identityPath: name
fields:
  name:
    path: name
    type: string
  projectId:
    path: project_id
    type: string
  state:
    path: state
    type: string
  uuid:
    path: uuid
    type: string
  labels:
    path: labels
    type: object
  createTime:
    path: createTime
    type: string
  config:
    path: config
    type: object
  storageConfig:
    path: storageConfig
    type: object
extensions:
  hook: gcp.resource
relationships:
- type: member_of
  targetType: compute.googleapis.com/Network
  targetIdPath: refs_compute_googleapis_com_Network
- type: member_of
  targetType: compute.googleapis.com/Subnetwork
  targetIdPath: refs_compute_googleapis_com_Subnetwork
- type: uses
  targetType: iam.googleapis.com/ServiceAccount
  targetIdPath: refs_iam_googleapis_com_ServiceAccount
- type: uses
  targetType: cloudkms.googleapis.com/CryptoKey
  targetIdPath: refs_cloudkms_googleapis_com_CryptoKey
- type: uses
  targetType: storage.googleapis.com/Bucket
  targetIdPath: refs_storage_googleapis_com_Bucket
actions:
  delete:
    operation: composer.projects.locations.environments.delete
    idempotency: readback
    waiter: gcp_operation
    readback: gcp_absent
    read:
      operation: composer.projects.locations.environments.get
      itemsPath: $
      identityPath: name
