package alicloud

const (
	CENInstanceNativeType                       = "ACS::CEN::CenInstance"
	CENBandwidthPackageNativeType               = "ACS::CEN::CenBandwidthPackage"
	CENTransitRouterNativeType                  = "ACS::CEN::TransitRouter"
	CENTransitRouterVPCAttachmentNativeType     = "ACS::CEN::TransitRouterVpcAttachment"
	CENTransitRouterVBRAttachmentNativeType     = "ACS::CEN::TransitRouterVbrAttachment"
	CENTransitRouterVPNAttachmentNativeType     = "ACS::CEN::TransitRouterVpnAttachment"
	CENTransitRouterECRAttachmentNativeType     = "ACS::CEN::TransitRouterEcrAttachment"
	CENTransitRouterPeerAttachmentNativeType    = "ACS::CEN::TransitRouterPeerAttachment"
	CENTransitRouterRouteTableNativeType        = "ACS::CEN::TransitRouterRouteTable"
	CENTransitRouterCidrNativeType              = "ACS::CEN::TransitRouterCidr"
	CENFlowLogNativeType                        = "ACS::CEN::Flowlog"
	CENRouteMapNativeType                       = "ACS::CEN::CenRouteMap"
	CENChildInstanceAttachmentNativeType        = "ACS::CEN::ChildInstanceAttachment"
	CENTransitRouterMulticastDomainNativeType   = "ACS::CEN::TransitRouterMulticastDomain"
	CENTrafficMarkingPolicyNativeType           = "ACS::CEN::TrafficMarkingPolicy"
	CENInterRegionTrafficQosPolicyNativeType    = "ACS::CEN::InterRegionTrafficQosPolicy"
	NormalizedCENZoneMappingsField              = "zoneMappings"
	NormalizedCENRegionIDField                  = "regionId"
	NormalizedCENInstanceIDField                = "cenId"
	NormalizedCENTransitRouterIDField           = "transitRouterId"
	NormalizedCENTransitRouterAttachmentIDField = "transitRouterAttachmentId"
	NormalizedCENTransitRouterRouteTableIDField = "transitRouterRouteTableId"
	NormalizedCENVPCIDField                     = "vpcId"
	NormalizedCENVBRIDField                     = "vbrId"
	NormalizedCENVPNIDField                     = "vpnId"
	NormalizedCENECRIDField                     = "ecrId"
	NormalizedCENPeerTransitRouterIDField       = "peerTransitRouterId"
	NormalizedCENPeerRegionIDField              = "peerRegionId"
	NormalizedCENBandwidthPackageIDField        = "cenBandwidthPackageId"
	NormalizedCENRouteTableAssociationsField    = "associations"
	NormalizedCENRouteTablePropagationsField    = "propagations"
	NormalizedCENRouteEntriesField              = "routeEntries"
	NormalizedCENPrefixListAssociationsField    = "prefixListAssociations"
	NormalizedCENRouteTableAggregationsField    = "aggregations"
)
