package alicloud

type localizedResourceDisplayName struct {
	zhCN string
	enUS string
}

// resourceDisplayNames contains the curated, self-contained name of every
// supported instance resource type. Each label is reviewed individually so
// clients can render it directly without composing product and type fragments.
var resourceDisplayNames = map[string]localizedResourceDisplayName{
	"ACS::ACK::Cluster":                               {zhCN: "ACK 集群", enUS: "ACK Cluster"},
	"ACS::ADB::DBCluster":                             {zhCN: "ADB 数仓版集群", enUS: "ADB Data Warehouse Cluster"},
	"ACS::ADB::DBClusterLakeVersion":                  {zhCN: "ADB 湖仓版集群", enUS: "ADB Lakehouse Cluster"},
	"ACS::ALB::LoadBalancer":                          {zhCN: "ALB 实例", enUS: "ALB Instance"},
	"ACS::APIG::Gateway":                              {zhCN: "云原生 API 网关", enUS: "Cloud-native API Gateway"},
	"ACS::ARMS::Environment":                          {zhCN: "ARMS VPC 环境", enUS: "ARMS VPC Environment"},
	"ACS::ARMS::GrafanaWorkspace":                     {zhCN: "Grafana 工作区", enUS: "Grafana Workspace"},
	"ACS::ARMS::Prometheus":                           {zhCN: "Prometheus 实例", enUS: "Prometheus Instance"},
	"ACS::ARMS::TraceApp":                             {zhCN: "ARMS 应用监控", enUS: "ARMS Application Monitoring"},
	"ACS::AckOne::Cluster":                            {zhCN: "ACK One 管控集群", enUS: "ACK One Control Plane Cluster"},
	"ACS::ActionTrail::Trail":                         {zhCN: "操作审计跟踪", enUS: "ActionTrail"},
	"ACS::AliKafka::Instance":                         {zhCN: "Kafka 实例", enUS: "Kafka Instance"},
	"ACS::Alidns::DnsGtmInstance":                     {zhCN: "DNS GTM 实例（新版）", enUS: "DNS GTM Instance (New)"},
	"ACS::Alidns::Domain":                             {zhCN: "云解析 DNS 域名", enUS: "Alibaba Cloud DNS Domain"},
	"ACS::Alidns::GtmInstance":                        {zhCN: "GTM 实例（旧版）", enUS: "GTM Instance (Legacy)"},
	"ACS::ApiGateway::Instance":                       {zhCN: "API 网关实例", enUS: "API Gateway Instance"},
	"ACS::BPStudio::Application":                      {zhCN: "云速搭应用", enUS: "CADT Application"},
	"ACS::Bastionhost::Instance":                      {zhCN: "堡垒机实例", enUS: "Bastionhost Instance"},
	"ACS::CBWP::CommonBandwidthPackage":               {zhCN: "共享带宽实例", enUS: "Shared Bandwidth Instance"},
	"ACS::CDN::Domain":                                {zhCN: "CDN 域名", enUS: "CDN Domain"},
	"ACS::CEN::CenBandwidthPackage":                   {zhCN: "云企业网带宽包", enUS: "CEN Bandwidth Package"},
	"ACS::CEN::CenInstance":                           {zhCN: "云企业网实例", enUS: "CEN Instance"},
	"ACS::CEN::TransitRouter":                         {zhCN: "CEN 转发路由器", enUS: "CEN Transit Router"},
	"ACS::CR::Instance":                               {zhCN: "容器镜像实例", enUS: "Container Registry Instance"},
	"ACS::ClickHouse::DBCluster":                      {zhCN: "ClickHouse 社区版集群", enUS: "ClickHouse Community Edition Cluster"},
	"ACS::ClickHouse::EnterpriseDBCluster":            {zhCN: "ClickHouse 企业版集群", enUS: "ClickHouse Enterprise Edition Cluster"},
	"ACS::CloudFirewall::Instance":                    {zhCN: "云防火墙实例", enUS: "Cloud Firewall Instance"},
	"ACS::CloudSSO::Group":                            {zhCN: "Cloud SSO 用户组", enUS: "Cloud SSO User Group"},
	"ACS::CloudStorageGateway::Gateway":               {zhCN: "云存储网关", enUS: "Cloud Storage Gateway"},
	"ACS::DBS::BackupPlan":                            {zhCN: "数据库备份计划", enUS: "Database Backup Plan"},
	"ACS::DCDN::Domain":                               {zhCN: "DCDN 加速域名", enUS: "DCDN Domain"},
	"ACS::DCDN::IpaDomain":                            {zhCN: "DCDN IPA 加速域名", enUS: "DCDN IPA Domain"},
	"ACS::DRDS::DBInstance":                           {zhCN: "PolarDB-X 1.0 实例", enUS: "PolarDB-X 1.0 Instance"},
	"ACS::DRDS::PolarDBXInstance":                     {zhCN: "PolarDB-X 2.0 实例", enUS: "PolarDB-X 2.0 Instance"},
	"ACS::DTS::Instance":                              {zhCN: "DTS 实例", enUS: "DTS Instance"},
	"ACS::DataHub::Project":                           {zhCN: "DataHub 项目", enUS: "DataHub Project"},
	"ACS::DataV::Workspace":                           {zhCN: "DataV 工作空间", enUS: "DataV Workspace"},
	"ACS::DataWorks::DwResourceGroup":                 {zhCN: "DataWorks 资源组", enUS: "DataWorks Resource Group"},
	"ACS::DataWorks::Project":                         {zhCN: "DataWorks 工作空间", enUS: "DataWorks Workspace"},
	"ACS::DdosBgp::Instance":                          {zhCN: "DDoS 原生防护实例", enUS: "Anti-DDoS Origin Instance"},
	"ACS::DdosCoo::Instance":                          {zhCN: "DDoS 高防实例", enUS: "Anti-DDoS Proxy Instance"},
	"ACS::Domain::Domain":                             {zhCN: "注册域名", enUS: "Registered Domain"},
	"ACS::EAIS::Instance":                             {zhCN: "EAIS 实例", enUS: "EAIS Instance"},
	"ACS::EBS::DedicatedBlockStorageCluster":          {zhCN: "块存储专属集群", enUS: "EBS Dedicated Cluster"},
	"ACS::EBS::DiskReplicaGroup":                      {zhCN: "云盘异步复制一致性组", enUS: "EBS Replication Group"},
	"ACS::EBS::DiskReplicaPair":                       {zhCN: "云盘异步复制对", enUS: "EBS Replication Pair"},
	"ACS::ECI::ContainerGroup":                        {zhCN: "ECI 容器组", enUS: "ECI Container Group"},
	"ACS::ECI::ImageCache":                            {zhCN: "ECI 镜像缓存", enUS: "ECI Image Cache"},
	"ACS::ECP::Instance":                              {zhCN: "弹性云手机实例", enUS: "Elastic Cloud Phone Instance"},
	"ACS::ECS::AutoSnapshotPolicy":                    {zhCN: "自动快照策略", enUS: "Auto Snapshot Policy"},
	"ACS::ECS::CapacityReservation":                   {zhCN: "ECS 容量预定", enUS: "ECS Capacity Reservation"},
	"ACS::ECS::DedicatedHost":                         {zhCN: "ECS 专有宿主机", enUS: "ECS Dedicated Host"},
	"ACS::ECS::Disk":                                  {zhCN: "ECS 云盘", enUS: "ECS Disk"},
	"ACS::ECS::ElasticityAssurance":                   {zhCN: "ECS 弹性保障", enUS: "ECS Elasticity Assurance"},
	"ACS::ECS::Image":                                 {zhCN: "镜像", enUS: "Image"},
	"ACS::ECS::Instance":                              {zhCN: "ECS 实例", enUS: "ECS Instance"},
	"ACS::ECS::KeyPair":                               {zhCN: "ECS 密钥对", enUS: "ECS SSH Key Pair"},
	"ACS::ECS::NetworkInterface":                      {zhCN: "弹性网卡", enUS: "Elastic Network Interface"},
	"ACS::ECS::SecurityGroup":                         {zhCN: "安全组", enUS: "Security Group"},
	"ACS::ECS::Snapshot":                              {zhCN: "快照", enUS: "Snapshot"},
	"ACS::EIP::EipAddress":                            {zhCN: "弹性公网 IP", enUS: "EIP"},
	"ACS::ENS::Instance":                              {zhCN: "ENS 实例", enUS: "ENS Instance"},
	"ACS::ESA::Site":                                  {zhCN: "ESA 站点", enUS: "ESA Site"},
	"ACS::ESS::ScalingGroup":                          {zhCN: "弹性伸缩组", enUS: "Auto Scaling Group"},
	"ACS::Eflo::Cluster":                              {zhCN: "智算灵骏集群", enUS: "Lingjun Cluster"},
	"ACS::Ehpc::Cluster":                              {zhCN: "E-HPC 集群", enUS: "E-HPC Cluster"},
	"ACS::Eipanycast::AnycastEipAddress":              {zhCN: "Anycast EIP 地址", enUS: "Anycast EIP"},
	"ACS::Elasticsearch::Instance":                    {zhCN: "Elasticsearch 实例", enUS: "Elasticsearch Instance"},
	"ACS::Elasticsearch::Logstash":                    {zhCN: "Logstash 实例", enUS: "Logstash Instance"},
	"ACS::EmrServerlessSpark::Workspace":              {zhCN: "EMR Serverless Spark 工作空间", enUS: "EMR Serverless Spark Workspace"},
	"ACS::ExpressConnect::PhysicalConnection":         {zhCN: "高速通道物理专线", enUS: "Express Connect Physical Connection"},
	"ACS::ExpressConnect::VirtualBorderRouter":        {zhCN: "高速通道 VBR", enUS: "Express Connect VBR"},
	"ACS::ExpressConnectRouter::ExpressConnectRouter": {zhCN: "高速通道 ECR", enUS: "Express Connect Router"},
	"ACS::FC::Service":                                {zhCN: "函数计算服务", enUS: "Function Compute Service"},
	"ACS::GWLB::LoadBalancer":                         {zhCN: "网关型负载均衡", enUS: "Gateway Load Balancer"},
	"ACS::GPDB::DBInstance":                           {zhCN: "AnalyticDB PostgreSQL 实例", enUS: "AnalyticDB for PostgreSQL Instance"},
	"ACS::Ga::Accelerator":                            {zhCN: "全球加速实例", enUS: "Global Accelerator Instance"},
	"ACS::Ga::BandwidthPackage":                       {zhCN: "全球加速带宽包", enUS: "Global Accelerator Bandwidth Package"},
	"ACS::GraphDatabase::DbInstance":                  {zhCN: "图数据库实例", enUS: "Graph Database Instance"},
	"ACS::HBR::HanaInstance":                          {zhCN: "SAP HANA 实例", enUS: "SAP HANA Instance"},
	"ACS::HBR::Vault":                                 {zhCN: "云备份存储库", enUS: "Cloud Backup Vault"},
	"ACS::HBase::Cluster":                             {zhCN: "HBase 集群", enUS: "HBase Cluster"},
	"ACS::Hologram::Instance":                         {zhCN: "Hologres 实例", enUS: "Hologres Instance"},
	"ACS::KMS::Key":                                   {zhCN: "KMS 密钥", enUS: "KMS Key"},
	"ACS::Lindorm::Instance":                          {zhCN: "Lindorm 实例", enUS: "Lindorm Instance"},
	"ACS::Live::Domain":                               {zhCN: "视频直播域名", enUS: "ApsaraVideo Live Domain"},
	"ACS::MSE::Cluster":                               {zhCN: "MSE 集群", enUS: "MSE Cluster"},
	"ACS::MSE::Gateway":                               {zhCN: "MSE 云原生网关", enUS: "MSE Cloud-native Gateway"},
	"ACS::MaxCompute::Project":                        {zhCN: "MaxCompute 项目", enUS: "MaxCompute Project"},
	"ACS::MessageService::Queue":                      {zhCN: "MNS 队列", enUS: "MNS Queue"},
	"ACS::MessageService::Topic":                      {zhCN: "MNS 主题", enUS: "MNS Topic"},
	"ACS::MongoDB::DBInstance":                        {zhCN: "MongoDB 实例", enUS: "MongoDB Instance"},
	"ACS::NAS::FileSystem":                            {zhCN: "NAS 文件系统", enUS: "NAS File System"},
	"ACS::NAT::NatGateway":                            {zhCN: "NAT 网关", enUS: "NAT Gateway"},
	"ACS::NAT::NatIp":                                 {zhCN: "NAT IP 地址", enUS: "NAT IP Address"},
	"ACS::NLB::LoadBalancer":                          {zhCN: "NLB 实例", enUS: "NLB Instance"},
	"ACS::OOS::Application":                           {zhCN: "OOS 应用", enUS: "OOS Application"},
	"ACS::OSS::Bucket":                                {zhCN: "OSS Bucket", enUS: "OSS Bucket"},
	"ACS::OTS::Instance":                              {zhCN: "Tablestore 实例", enUS: "Tablestore Instance"},
	"ACS::OceanBase::Instance":                        {zhCN: "OceanBase 实例", enUS: "OceanBase Instance"},
	"ACS::Ons::Instance":                              {zhCN: "RocketMQ 4.x 实例", enUS: "RocketMQ 4.x Instance"},
	"ACS::OpenSearch::AppGroup":                       {zhCN: "OpenSearch 应用", enUS: "OpenSearch Application"},
	"ACS::PAI::Service":                               {zhCN: "PAI 服务", enUS: "PAI Service"},
	"ACS::PolarDB::DBCluster":                         {zhCN: "PolarDB 集群", enUS: "PolarDB Cluster"},
	"ACS::PrivateLink::VpcEndpoint":                   {zhCN: "私网连接终端节点", enUS: "PrivateLink Endpoint"},
	"ACS::PrivateLink::VpcEndpointService":            {zhCN: "私网连接终端节点服务", enUS: "PrivateLink Endpoint Service"},
	"ACS::PrivateZone::Zone":                          {zhCN: "云解析 PrivateZone", enUS: "PrivateZone"},
	"ACS::RAM::Group":                                 {zhCN: "RAM 用户组", enUS: "RAM User Group"},
	"ACS::RAM::Policy":                                {zhCN: "RAM 权限策略", enUS: "RAM Policy"},
	"ACS::RAM::Role":                                  {zhCN: "RAM 角色", enUS: "RAM Role"},
	"ACS::RAM::User":                                  {zhCN: "RAM 用户", enUS: "RAM User"},
	"ACS::RDS::DBInstance":                            {zhCN: "RDS 实例", enUS: "RDS Instance"},
	"ACS::ROS::Stack":                                 {zhCN: "ROS 资源栈", enUS: "ROS Stack"},
	"ACS::ROS::StackGroup":                            {zhCN: "ROS 资源栈组", enUS: "ROS Stack Group"},
	"ACS::RTC::Application":                           {zhCN: "RTC 应用", enUS: "RTC Application"},
	"ACS::RealtimeCompute::VvpInstance":               {zhCN: "实时计算 Flink 工作空间", enUS: "Realtime Compute for Apache Flink Workspace"},
	"ACS::Redis::DBInstance":                          {zhCN: "Tair 实例", enUS: "Tair Instance"},
	"ACS::ResourceManager::ResourceDirectory":         {zhCN: "资源目录", enUS: "Resource Directory"},
	"ACS::RocketMQ::Instance":                         {zhCN: "RocketMQ 5.x 实例", enUS: "RocketMQ 5.x Instance"},
	"ACS::SCDN::Domain":                               {zhCN: "SCDN 域名", enUS: "SCDN Domain"},
	"ACS::SDDP::Instance":                             {zhCN: "数据安全中心实例", enUS: "Data Security Center Instance"},
	"ACS::SLB::LoadBalancer":                          {zhCN: "CLB 实例", enUS: "CLB Instance"},
	"ACS::SLS::Project":                               {zhCN: "日志服务 Project", enUS: "Simple Log Service Project"},
	"ACS::SMS::Template":                              {zhCN: "短信模板", enUS: "SMS Template"},
	"ACS::SSLCertificatesService::Certificate":        {zhCN: "SSL 证书", enUS: "SSL Certificate"},
	"ACS::SWAS::Instance":                             {zhCN: "轻量应用服务器实例", enUS: "Simple Application Server Instance"},
	"ACS::SelectDB::DBInstance":                       {zhCN: "云数据库 SelectDB 实例", enUS: "SelectDB Instance"},
	"ACS::TSDB::Instance":                             {zhCN: "时序数据库实例", enUS: "Time Series Database Instance"},
	"ACS::ThreatDetection::Instance":                  {zhCN: "云安全中心实例", enUS: "Security Center Instance"},
	"ACS::VOD::Domain":                                {zhCN: "视频点播域名", enUS: "ApsaraVideo VOD Domain"},
	"ACS::VPC::Ipv4Gateway":                           {zhCN: "IPv4 网关", enUS: "IPv4 Gateway"},
	"ACS::VPC::Ipv6Address":                           {zhCN: "IPv6 地址", enUS: "IPv6 Address"},
	"ACS::VPC::Ipv6Gateway":                           {zhCN: "IPv6 网关", enUS: "IPv6 Gateway"},
	"ACS::VPC::NetworkAcl":                            {zhCN: "VPC 网络 ACL", enUS: "VPC Network ACL"},
	"ACS::VPC::PeerConnection":                        {zhCN: "VPC 对等连接", enUS: "VPC Peering Connection"},
	"ACS::VPC::RouteTable":                            {zhCN: "VPC 路由表", enUS: "VPC Route Table"},
	"ACS::VPC::VPC":                                   {zhCN: "专有网络", enUS: "VPC"},
	"ACS::VPC::VSwitch":                               {zhCN: "交换机", enUS: "vSwitch"},
	"ACS::VPN::CustomerGateway":                       {zhCN: "VPN 用户网关", enUS: "VPN Customer Gateway"},
	"ACS::VPN::VpnGateway":                            {zhCN: "VPN 网关", enUS: "VPN Gateway"},
}

func catalogDisplayNames(nativeType string) (map[string]string, bool) {
	names, ok := resourceDisplayNames[nativeType]
	if !ok {
		return nil, false
	}
	return map[string]string{
		"zh-CN": names.zhCN,
		"en-US": names.enUS,
	}, true
}
