package catalog

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/loomx-ai/steward/internal/core/asset"
)

const GeneratedHeader = "// Code generated by steward cataloggen. DO NOT EDIT.\n"

type Importer interface {
	Import(provider asset.Provider, sourceURI string, source []byte) (Catalog, error)
}

type OpenAPIImporter struct{}

func ImportOfficial(format string, provider asset.Provider, sourceURI string, source []byte) (Catalog, error) {
	switch strings.ToLower(strings.TrimSpace(format)) {
	case "openapi":
		return OpenAPIImporter{}.Import(provider, sourceURI, source)
	case "smithy":
		return SmithyImporter{}.Import(provider, sourceURI, source)
	default:
		return Catalog{}, fmt.Errorf("unsupported official metadata format %q", format)
	}
}

type openAPIDocument struct {
	Info struct {
		Title string `json:"title"`
	} `json:"info"`
	Paths            map[string]map[string]openAPIOperation `json:"paths"`
	ResourceTypes    []openAPIResourceType                  `json:"x-resource-types"`
	ProductEndpoints map[string]map[string]string           `json:"x-product-endpoints"`
}

type openAPIOperation struct {
	OperationID   string         `json:"operationId"`
	OperationName string         `json:"x-operation-name"`
	Input         map[string]any `json:"x-input-schema"`
	Output        map[string]any `json:"x-output-schema"`
	Pagination    *Pagination    `json:"x-pagination"`
	Call          *OperationCall `json:"x-operation-call"`
	Destructive   *bool          `json:"x-destructive"`
}

type openAPIResourceType struct {
	NativeType  string            `json:"nativeType"`
	Class       string            `json:"class"`
	DisplayName string            `json:"displayName"`
	ScopeKinds  []asset.ScopeKind `json:"scopeKinds"`
}

func (OpenAPIImporter) Import(provider asset.Provider, sourceURI string, source []byte) (Catalog, error) {
	if provider == "" {
		return Catalog{}, fmt.Errorf("provider is required")
	}
	var document openAPIDocument
	decoder := json.NewDecoder(bytes.NewReader(source))
	decoder.UseNumber()
	if err := decoder.Decode(&document); err != nil {
		return Catalog{}, fmt.Errorf("decode OpenAPI source: %w", err)
	}
	checksum := sha256.Sum256(source)
	c := Catalog{
		Provider: provider,
		Source: Source{
			Format:    "openapi",
			URI:       sourceURI,
			Checksum:  hex.EncodeToString(checksum[:]),
			Generator: "steward/cataloggen",
		},
	}
	for path, methods := range document.Paths {
		for method, operation := range methods {
			if operation.OperationID == "" || !isHTTPMethod(method) {
				continue
			}
			operationName := strings.TrimSpace(operation.OperationName)
			if operationName == "" {
				operationName = operation.OperationID
			}
			destructive := isDestructiveOperation(operationName, method)
			if operation.Destructive != nil {
				destructive = *operation.Destructive
			}
			call := operation.Call
			if call != nil {
				cloned := *call
				cloned.EndpointOverrides = cloneStringMap(call.EndpointOverrides)
				cloned.SiteEndpoints = cloneSiteEndpointMap(call.SiteEndpoints)
				cloned.EndpointParameters = append([]string(nil), call.EndpointParameters...)
				cloned.HostParameters = append([]string(nil), call.HostParameters...)
				cloned.HeaderParameters = append([]string(nil), call.HeaderParameters...)
				cloned.RawPathParameters = append([]string(nil), call.RawPathParameters...)
				if cloned.EndpointOverrides == nil &&
					len(document.ProductEndpoints[call.Product]) > 0 {
					cloned.EndpointOverrides = map[string]string{}
				}
				for region, endpoint := range document.ProductEndpoints[call.Product] {
					cloned.EndpointOverrides[region] = endpoint
				}
				call = &cloned
			}
			c.Operations = append(c.Operations, Operation{
				ID:           qualifiedOperationID(document.Info.Title, operation.OperationID),
				Name:         operationName,
				Service:      document.Info.Title,
				Method:       strings.ToUpper(method),
				Path:         path,
				Destructive:  destructive,
				InputSchema:  operation.Input,
				OutputSchema: operation.Output,
				Pagination:   operation.Pagination,
				Call:         call,
			})
		}
	}
	for _, resourceType := range document.ResourceTypes {
		c.ResourceTypes = append(c.ResourceTypes, ResourceType{
			NativeType:  resourceType.NativeType,
			Class:       resourceType.Class,
			DisplayName: resourceType.DisplayName,
			ScopeKinds:  append([]asset.ScopeKind(nil), resourceType.ScopeKinds...),
		})
	}
	normalize(&c)
	return c, nil
}

type SmithyImporter struct{}

type smithyDocument struct {
	Shapes        map[string]smithyShape `json:"shapes"`
	ResourceTypes []openAPIResourceType  `json:"x-resource-types"`
}

type smithyShape struct {
	Type   string         `json:"type"`
	Traits map[string]any `json:"traits"`
}

func (SmithyImporter) Import(provider asset.Provider, sourceURI string, source []byte) (Catalog, error) {
	var document smithyDocument
	if err := json.Unmarshal(source, &document); err != nil {
		return Catalog{}, fmt.Errorf("decode Smithy source: %w", err)
	}
	c := newCatalog(provider, "smithy", sourceURI, source)
	for shapeID, shape := range document.Shapes {
		if shape.Type != "operation" {
			continue
		}
		name := shapeID
		if separator := strings.LastIndex(name, "#"); separator >= 0 {
			name = name[separator+1:]
		}
		operation := Operation{ID: shapeID, Name: name, Service: smithyNamespace(shapeID)}
		if httpTrait, ok := shape.Traits["smithy.api#http"].(map[string]any); ok {
			operation.Method, _ = httpTrait["method"].(string)
			operation.Path, _ = httpTrait["uri"].(string)
		}
		operation.Destructive = isDestructiveOperation(operation.Name, operation.Method)
		c.Operations = append(c.Operations, operation)
	}
	appendResourceTypes(&c, document.ResourceTypes)
	normalize(&c)
	return c, nil
}

func MarshalGenerated(c Catalog) ([]byte, error) {
	cloned, err := cloneCatalog(c)
	if err != nil {
		return nil, err
	}
	c = cloned
	normalize(&c)
	c.ContentChecksum, err = catalogContentChecksum(c)
	if err != nil {
		return nil, err
	}
	payload, err := json.MarshalIndent(c, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal generated catalog: %w", err)
	}
	result := make([]byte, 0, len(GeneratedHeader)+len(payload)+1)
	result = append(result, GeneratedHeader...)
	result = append(result, payload...)
	result = append(result, '\n')
	return result, nil
}

func UnmarshalGenerated(source []byte) (Catalog, error) {
	if !bytes.HasPrefix(source, []byte(GeneratedHeader)) {
		return Catalog{}, fmt.Errorf("generated catalog header is missing")
	}
	payload := source[len(GeneratedHeader):]
	var c Catalog
	decoder := json.NewDecoder(bytes.NewReader(payload))
	decoder.DisallowUnknownFields()
	if err := decoder.Decode(&c); err != nil {
		return Catalog{}, fmt.Errorf("decode generated catalog: %w", err)
	}
	normalize(&c)
	claimed := c.ContentChecksum
	if claimed == "" {
		return Catalog{}, fmt.Errorf("generated catalog content checksum is missing")
	}
	actual, err := catalogContentChecksum(c)
	if err != nil {
		return Catalog{}, err
	}
	if claimed != actual {
		return Catalog{}, fmt.Errorf("generated catalog content checksum mismatch")
	}
	return c, nil
}

func catalogContentChecksum(c Catalog) (string, error) {
	c.ContentChecksum = ""
	normalize(&c)
	payload, err := json.Marshal(c)
	if err != nil {
		return "", fmt.Errorf("hash generated catalog: %w", err)
	}
	digest := sha256.Sum256(payload)
	return hex.EncodeToString(digest[:]), nil
}

func normalize(c *Catalog) {
	sort.Slice(c.Operations, func(i, j int) bool {
		if c.Operations[i].Key() != c.Operations[j].Key() {
			return c.Operations[i].Key() < c.Operations[j].Key()
		}
		if c.Operations[i].Name != c.Operations[j].Name {
			return c.Operations[i].Name < c.Operations[j].Name
		}
		if c.Operations[i].Path != c.Operations[j].Path {
			return c.Operations[i].Path < c.Operations[j].Path
		}
		return c.Operations[i].Method < c.Operations[j].Method
	})
	sort.Slice(c.ResourceTypes, func(i, j int) bool {
		return c.ResourceTypes[i].NativeType < c.ResourceTypes[j].NativeType
	})
	for i := range c.ResourceTypes {
		sort.Slice(c.ResourceTypes[i].ScopeKinds, func(left, right int) bool {
			return c.ResourceTypes[i].ScopeKinds[left] < c.ResourceTypes[i].ScopeKinds[right]
		})
	}
}

func isHTTPMethod(method string) bool {
	switch strings.ToLower(method) {
	case "get", "post", "put", "patch", "delete", "head", "options":
		return true
	default:
		return false
	}
}

func cloneStringMap(values map[string]string) map[string]string {
	if len(values) == 0 {
		return nil
	}
	cloned := make(map[string]string, len(values))
	for key, value := range values {
		cloned[key] = value
	}
	return cloned
}

func cloneSiteEndpointMap(
	values map[asset.ConnectionSite]string,
) map[asset.ConnectionSite]string {
	if len(values) == 0 {
		return nil
	}
	cloned := make(map[asset.ConnectionSite]string, len(values))
	for key, value := range values {
		cloned[key] = value
	}
	return cloned
}

func isDestructiveOperation(operationID, method string) bool {
	name := strings.ToLower(operationID)
	return strings.EqualFold(method, "delete") ||
		strings.HasPrefix(name, "delete") ||
		strings.HasPrefix(name, "remove") ||
		strings.HasPrefix(name, "terminate") ||
		strings.HasPrefix(name, "destroy")
}

func newCatalog(provider asset.Provider, format, sourceURI string, source []byte) Catalog {
	checksum := sha256.Sum256(source)
	return Catalog{
		Provider: provider,
		Source: Source{
			Format:    format,
			URI:       sourceURI,
			Checksum:  hex.EncodeToString(checksum[:]),
			Generator: "steward/cataloggen",
		},
	}
}

func appendResourceTypes(c *Catalog, resourceTypes []openAPIResourceType) {
	for _, resourceType := range resourceTypes {
		c.ResourceTypes = append(c.ResourceTypes, ResourceType{
			NativeType:  resourceType.NativeType,
			Class:       resourceType.Class,
			DisplayName: resourceType.DisplayName,
			ScopeKinds:  append([]asset.ScopeKind(nil), resourceType.ScopeKinds...),
		})
	}
}

func smithyNamespace(shapeID string) string {
	if separator := strings.LastIndex(shapeID, "#"); separator >= 0 {
		return shapeID[:separator]
	}
	return ""
}

func qualifiedOperationID(service, name string) string {
	if service == "" || strings.HasPrefix(name, service+".") {
		return name
	}
	return service + "." + name
}
